### ISSUE TITLE
IHelper Implementation Mismatch

### ISSUE THREAD

**Issue by abilson** [tsdservices/Gravity#1]
The Gravity.Base.AppConfigConnectionHelper implements Relativity.API.IHelper, however, it's missing four methods on the interface of the 9.4.398.62 assembly:

- public string ResourceDBPrepend()
- public string ResourceDBPrepend(IDBContext context)
- public string GetSchemalessResourceDataBasePrepend(IDBContext context)
- public Guid GetGuid(int workspaceID, int artifactID)

**Comment by mrobustelli** [comment]
I think it should throw a not implemented error in the compile? or maybe was a versioning thing.  Probably versioning.

Also I have updated the test helpers in the relativity-test-helper project to handle some of the Helper stuff.  Waiting on pull request approval for it.
