### ISSUE TITLE
Switch Relativity dependencies to use Nuget packages

### ISSUE THREAD

**Issue by Arithmomaniac** [tsdservices/Gravity#10]
This is a prerequisite for Continuous Integration, in addition to just making development easier in general. The packages are still a bit of a WIP, but the ones currently needed are:

- Relativity.Rsapi (kCura.Relativity.Client.dll)
- Relativity.API (Relativity.API.dll)
- Relativity.RowDataGateway (kCura.Data.RowDataGateway.dll)

**Comment by jacobmalliet** [comment]
Fixed
