### ISSUE TITLE
Move Document-specific stuff out of the RSAPI DAO

### ISSUE THREAD

**Issue by Arithmomaniac** [tsdservices/Gravity#20]
There are a couple of `Document`-based methods at the end of  the RSAPI DAO: https://github.com/tsdservices/Gravity/blob/835bea60cd23ff7e4b8a4727874dfbb357644fc4/Gravity/Gravity/DAL/RSAPI/RsapiDao.Get.cs#L332 These should be moved to their own class.

**Comment by Arithmomaniac** [comment]
Partial group has been done on this in #21 by making `RsapiDao` a partial class and moving the Document-based logic to its own file.

**Comment by jacobmalliet** [comment]
It might make sense to move document related queries to a new class entirely instead of just another partial. Document queries seem to specific for just a general `RsapiDao ` object
