### ISSUE TITLE
Changes to Gravity.Test project

### ISSUE THREAD

**Issue by ppande1020** [tsdservices/Gravity#39]
1. The Readme file says to install an application for setting up the Gravity.test project which is fine but to make this agnostic let's use 'ImportApplication' keyword located here - https://github.com/relativitydev/relativity-test-helpers/blob/master/Source/Relativity.Test.Helpers/Relativity.Test.Helpers/Application/ApplicationHelpers.cs
This will import the application for you everytime the test runs.

2. I also had to hard code my workspace id in the app.config file. We recommend you create a workspace every time these tests are run so the test doesn't depend on a user doing manual work to set up the data. The create workspace helper is located here -  https://github.com/relativitydev/relativity-test-helpers/blob/master/Source/Relativity.Test.Helpers/Relativity.Test.Helpers/WorkspaceHelpers/CreateWorkspace.cs

3 If you are setting up your workspace everytime you run a test, you want to delete your workspace so you clean up everytime a test successfully passes.  Some delete workspace helpers we recommend are located here - https://github.com/relativitydev/relativity-test-helpers/blob/master/Source/Relativity.Test.Helpers/Relativity.Test.Helpers/WorkspaceHelpers/DeleteWorkspace.cs

4. It also looks like we also are hard-coding an artifact id of the RDO we are trying to query. Once the RDO's are uploaded into an instance of Relativity through ADS, we can make a call to retrieve the artifact ID of the RDO.

5. Although the visual studio testing framework works out well, since we use Nunit here at Relativity, we highly recommend Nunit.

**Comment by Arithmomaniac** [comment]
Along these lines, once all of these are implemented, it should be possible to delete the Gravity.Demo project and solution (as it would be incorporated into test setup).

**Comment by mrobustelli** [comment]
Made some progress on the plane.  Hope I can get more done soon!

**Comment by ppande1020** [comment]
Ideally, yes everything in the Gravity.Demo should be added to the test setup.

**Comment by ppande1020** [comment]
@mrobustelli What branch are you working on?

**Comment by mrobustelli** [comment]
TestingAndCI

**Comment by Arithmomaniac** [comment]
Being worked on in #48,

**Comment by Arithmomaniac** [comment]
@ppande1020 This is closeable now, yes?

**Comment by mrobustelli** [comment]
These changes are pushed into develop.  Removed the demo app, added the automation of the creation of the test data.
