### ISSUE TITLE
Support for Execution Identity in RsapiDao

### ISSUE THREAD

**Issue by jacobmalliet** [tsdservices/Gravity#4]
One major feature we need with Gravity is the ability to set the current `ExecutionIdentity`. Adding this in seems easy enough I just wanted to check which route the fix should be made. 

This is the current signature for creating an RsapiDao:

`public RsapiDao(IHelper helper, int workspaceId, InvokeWithRetrySettings invokeWithRetrySettings = null)`

In my eyes the ideal signature would be 
`public RsapiDao(IHelper helper, int workspaceId, ExecutionIdentity executionIdentity, InvokeWithRetrySettings invokeWithRetrySettings = null)`

My only concern here would be that this is a breaking change and would cause some issues for people upgrading (Currently this would only affect TSD). One potential solution would be adding the above signature and keeping the old one there as well. Possibly even deprecating the original constructor and removing it at a future time. 

Thoughts?

**Comment by abilson** [comment]
Excellent idea.

I'd prefer the execution identity to be closer to the data retrieval myself, but I'm not sure there's a decent implementation strategy for this because the execution identity is set at proxy instantiation. Some designs may require both admin and current user access methods, so it'd be nice to specify the identity at or near the method call rather than passing around two instantiated RsapiDao objects with different execution identities. Just a rant :)

**Comment by jacobmalliet** [comment]
With the proxy being generated for each request we could open up the ExecutionIdentity property on RsapiDao to be public. This would allow users to change the identity prior to making the call.

**Comment by mrobustelli** [comment]
What about the idea of making that an optional parameter after the first optional parameter? 
`public RsapiDao(IHelper helper, int workspaceId, InvokeWithRetrySettings invokeWithRetrySettings = null, ExecutionIdentity executionIdentity = ExecutionIdentity.System)`

This would not be a breaking change and still give you the flexibility right?

**Comment by jacobmalliet** [comment]
That was my first thought but I felt like ExecutionIdentity was important enough that it shouldn't be an optional parameter. Especially with the optional parameter defaulting to the most open of permissions.

**Comment by abilson** [comment]
I agree with Jacob. While an optional parameter would make the constructor more flexible, a new Relativity developer may overlook the fact that they're using Admin permissions by default. If anything, we'd want to offer current user permissions by default, with Admin as optional.

**Comment by mrobustelli** [comment]
So this is where we will need TSD to chime in as well.  Especially when we are starting up, I'm sure there will be a lot of changes quickly.  All the points you make about defaulting to system, and developers overlooking that, we have to be considerate of breaking the existing contract.   Right now, I feel like TSD has the most skin in the game, cause they will have to change their exiting stuff, so I feel like we need them to chime in.  What about an overloaded constructor?  That could work right?

**Comment by jacobmalliet** [comment]
That is how I made the pull request as is. I left the existing constructor and added an Obsolete attribute to it. This way all existing code will not be broken but they would get a compiler warning about the need to switch over to the other one.

**Comment by mrobustelli** [comment]
Then what the hell am I talking about?  Sorry must have missed that.  Sorry for the confusion.  Just took me a little longer to get there. :(
