### ISSUE TITLE
Update client object for unit tests

### ISSUE THREAD

**Issue by ppande1020** [tsdservices/Gravity#40]
We cant mock the client object when the client is created through the Helper. We found out internally through the platform team the reason we were not able to do that was because we are not able to stub out some of the properties when the client gets set through a Helper.

We recommend you use the IRsapiRepositoryGroup to create a client for different object types. This is an example of how we have created the client object - https://github.com/relativitydev/admin-migration-utility/blob/master/Source/Code/AdminMigrationUtility/AdminMigrationUtility/AdminMigrationUtility.Helpers/Rsapi/RSAPIiRepositoryGroup.cs

**Comment by mrobustelli** [comment]
Changes made and pushed to develop
