### ISSUE TITLE
Change default branch to development

### ISSUE THREAD

**Issue by Arithmomaniac** [tsdservices/Gravity#52]
Despite all development being against the `development` branch, the default on the website (e.g. tree view, pull requests) is still `master`. We should [change that](https://help.github.com/articles/setting-the-default-branch/).

**Comment by mrobustelli** [comment]
Totally agree.  I tried to do this and it got a message saying "updating the default branch can have unintended consequences."  Any ideas what those might be?  Once all the PRs are done, I'm cool doing a pull then updating the default branch regardless of consequences.

**Comment by Arithmomaniac** [comment]
The main one is that people get `devlopment` when they clone your project - which, at the current level of instability, is what you would want anyways.

**Comment by mrobustelli** [comment]
Sorry if my comment caused any confusion.  I am totally on board with this.  I just want to finish out the open pull requests, get a clean copy for back up purposes, then make the change.  The warning when I went to go make the change made me nervous.  No sure what the "unintended consequences" are. Just want everything in a "clean" state to make backing out of any issues as easy as possible if something comes up.

**Comment by mrobustelli** [comment]
done, no apparent "unintended consequences"
