### ISSUE TITLE
Add paging to queries

### ISSUE THREAD

**Issue by Arithmomaniac** [tsdservices/Gravity#8]
Currently, [RsapiDao.GetRDOs(Condition)](https://github.com/tsdservices/Gravity/blob/master/Gravity/Gravity/DAL/RSAPI/RsapiDao.Get.cs#L60) returns a `List<T>` and pulls all items down at once.

In order to enable handling of large sets, it would be better to use an `IEnumerable<T>` for queries, and pull results by paging. The general idea can be seen in the following code snippet we have used before at Milyli:

```csharp
var initialResultSet = repo.Query(query, pageLength);

foreach (var result in initialResultSet.Results)
    yield return result;

string queryToken = initialResultSet.QueryToken;

// Iterate though all remaining pages
var totalCount = initialResultSet.TotalCount;
int currentPosition = pageLength + 1;

while (currentPosition <= totalCount)
{
    var subsetResult = repo.QuerySubset(queryToken, currentPosition, pageLength);
    foreach (var result in subsetResult.Results)
        yield return result;

    currentPosition += pageLength;
}
```

The paging could be set as a global configuration and/or on the specific call, and fallback to "no paging" if not set.

**Comment by Arithmomaniac** [comment]
I've started work on this: [Arithmomaniac/Gravity/feature/Paging_8](https://github.com/Arithmomaniac/Gravity/tree/feature/Paging_8)

**Comment by ggachevski** [comment]
Very clean, very useful -- necessary, I should say.

Since I am on the direct-SQL calls wave right now (under #24), this Paging will be well handled by SQL server too, so same method signatures will remain and you will be able to do this as easily (and much more quickly) via a SQL-based implementation, soon.

**Comment by Arithmomaniac** [comment]
Notes from the 2017-12-13 call:
- Implementation in the RsapiDao should be backed by a `QueryAll` or `QueryPaged` extension method for RSAPI, which would do the logic above.
- Someone asked if we could make this an overload for `Query` so that the `List` version could be marked with an `Obsolete` attribute. I don't think so; you can overload for different parameters, but not for different return types.
